# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FarmTimer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FarmTimer
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Swiftlint'

  target 'FarmTimerTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
